version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      # build the application image
      - run:
          command: docker build -f ./docker/alpine/Dockerfile -t cquran.my.id:5000/wigglypuff . && docker push cquran.my.id:5000/wigglypuff
          no_output_timeout: 1h
